// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsrUsF6X8cKbVi38qFc_rPjg-ErXlQ2k',
    appId: '1:22209321914:android:9de27f3ca926528fd85b83',
    messagingSenderId: '22209321914',
    projectId: 'hope-project-diploma',
    databaseURL: 'https://hope-project-diploma-default-rtdb.firebaseio.com',
    storageBucket: 'hope-project-diploma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg2a7ObSnZ4ENZjGlOb5J4YbMlJKItFW8',
    appId: '1:22209321914:ios:a9cdc1634020f48bd85b83',
    messagingSenderId: '22209321914',
    projectId: 'hope-project-diploma',
    databaseURL: 'https://hope-project-diploma-default-rtdb.firebaseio.com',
    storageBucket: 'hope-project-diploma.appspot.com',
    androidClientId: '22209321914-uqv31hluh2lmepqn5k72qfbdaprf3843.apps.googleusercontent.com',
    iosClientId: '22209321914-jisbf6j1b2su2rpe375aq6uficf3u9ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopeProject',
  );
}
